[package]
name = "vendedor"
version = "0.1.0"
edition = "2021"

[dependencies]
zero = "0.1.3"
zero_git = { git = "https://github.com/nrc/zero.git", package = "zero", rev = "6fe64e981ce1e4d07c5cffec3019b5128af4a7b7" }

colored_json = { git = "https://github.com/ctron/colored_json" }
